import { Certificate, CertificateStatus, BlockchainStatus, ExternalCredentialStatus } from "@/types/certificate";

/**
 * Authoritative synthetic demo certificates for judge demonstration and testing.
 * Backed by completed demo projects (demo_proj_7 WasteWise and demo_proj_8 SkillMatch)
 * with complete originality checks, eligibility snapshots, and public verification IDs.
 */
export const SYNTHETIC_DEMO_CERTIFICATES: Certificate[] = [
  {
    id: "cert_demo_wastewise_1",
    verificationId: "SB-DEMO-WW95-2026",
    projectId: "demo_proj_7",
    applicationId: "demo_app_7",
    problemId: "demo_prob_1",
    studentId: "student_demo_uid",
    studentName: "Aarav Sharma",
    projectTitle: "WasteWise — Waste Classification & Collection Optimization",
    problemTitle: "Autonomous Municipal Waste Sorting & Route Optimization",
    institution: "SynergyBridge Demo Institute",
    department: "Computer Science & AI",
    course: "B.Tech",
    academicCredits: 4,
    issuedAt: "2026-08-20T10:00:00.000Z",
    status: CertificateStatus.ISSUED,
    certificateHash: "0x8e5f2a1b9c3d4e7f6a5b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f",
    blockchainStatus: BlockchainStatus.MOCK,
    blockchainTransactionId: "0x9a4f...3c82 (Simulated Polygon PoS)",
    digiLockerStatus: ExternalCredentialStatus.MOCK,
    abcStatus: ExternalCredentialStatus.MOCK,
    originalityScore: 96,
    originalityReportId: "cg_orig_7",
    issuerId: "faculty_demo_uid",
    issuerName: "Prof. Vikram Joshi",
    isDemo: true,
    eligibilitySnapshot: {
      taskCompletionPercentage: 100,
      completedMilestones: true,
      originalityScore: 96,
      eligibilityCheckedAt: "2026-08-20T09:45:00.000Z",
    },
    createdAt: "2026-08-20T10:00:00.000Z",
    updatedAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "cert_demo_skillmatch_1",
    verificationId: "SB-DEMO-SM92-2026",
    projectId: "demo_proj_8",
    applicationId: "demo_app_8",
    problemId: "demo_prob_3",
    studentId: "student_demo_uid",
    studentName: "Aarav Sharma",
    projectTitle: "SkillMatch — Multi-Disciplinary Skills-Based Match Platform",
    problemTitle: "Adaptive Multi-Disciplinary Engineering Problem Matching Engine",
    institution: "SynergyBridge Demo Institute",
    department: "Computer Science & AI",
    course: "B.Tech",
    academicCredits: 4,
    issuedAt: "2026-08-22T14:30:00.000Z",
    status: CertificateStatus.ISSUED,
    certificateHash: "0x7a4b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    blockchainStatus: BlockchainStatus.MOCK,
    blockchainTransactionId: "0x7b1e...4d91 (Simulated Polygon PoS)",
    digiLockerStatus: ExternalCredentialStatus.MOCK,
    abcStatus: ExternalCredentialStatus.MOCK,
    originalityScore: 92,
    originalityReportId: "cg_orig_8",
    issuerId: "faculty_demo_uid",
    issuerName: "Prof. Vikram Joshi",
    isDemo: true,
    eligibilitySnapshot: {
      taskCompletionPercentage: 100,
      completedMilestones: true,
      originalityScore: 92,
      eligibilityCheckedAt: "2026-08-22T14:15:00.000Z",
    },
    createdAt: "2026-08-22T14:30:00.000Z",
    updatedAt: "2026-08-22T14:30:00.000Z",
  }
];
