import { Achievement, AchievementCategory, AchievementRarity } from "@/types/gamification";

export const XP_REWARDS = {
  PROFILE_COMPLETED: 50,
  FIRST_SKILLS_ADDED: 25,
  APPLICATION_SUBMITTED: 20,
  APPLICATION_ACCEPTED: 100,
  TEAM_CREATED: 25,
  TEAM_JOINED: 15,
  TASK_COMPLETED: 10,
  MILESTONE_COMPLETED: 50,
  MENTOR_FEEDBACK_RECEIVED: 20,
  PROJECT_COMPLETED: 250,
  LEARNING_PATH_ITEM_COMPLETED: 15,
  PROBLEM_SOLVED: 100, // Equivalent to Project completion in SynergyBridge MVP context
};

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "profile-pioneer",
    name: "Profile Pioneer",
    description: "Student profile reaches 100% completeness.",
    category: AchievementCategory.PROFILE,
    rarity: AchievementRarity.COMMON,
    xpReward: 50,
    criteria: { type: "PROFILE_COMPLETED", target: 1 },
    active: true,
  },
  {
    id: "skill-builder",
    name: "Skill Builder",
    description: "Have 5 taxonomy-backed skills with proficiency.",
    category: AchievementCategory.LEARNING,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 75,
    criteria: { type: "SKILLS_COUNT", target: 5 },
    active: true,
  },
  {
    id: "problem-explorer",
    name: "Problem Explorer",
    description: "Submit 5 applications.",
    category: AchievementCategory.PROBLEM_SOLVING,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 100,
    criteria: { type: "APPLICATIONS_SUBMITTED", target: 5 },
    active: true,
  },
  {
    id: "team-player",
    name: "Team Player",
    description: "Successfully participate in 3 teams.",
    category: AchievementCategory.TEAMWORK,
    rarity: AchievementRarity.RARE,
    xpReward: 100,
    criteria: { type: "TEAMS_JOINED", target: 3 },
    active: true,
  },
  {
    id: "project-starter",
    name: "Project Starter",
    description: "Complete your first project.",
    category: AchievementCategory.PROJECT,
    rarity: AchievementRarity.RARE,
    xpReward: 250,
    criteria: { type: "PROJECTS_COMPLETED", target: 1 },
    active: true,
  },
  {
    id: "project-master",
    name: "Project Master",
    description: "Complete 5 projects.",
    category: AchievementCategory.PROJECT,
    rarity: AchievementRarity.EPIC,
    xpReward: 500,
    criteria: { type: "PROJECTS_COMPLETED", target: 5 },
    active: true,
  },
  {
    id: "consistent-learner",
    name: "Consistent Learner",
    description: "Achieve a 7-day activity streak.",
    category: AchievementCategory.CONSISTENCY,
    rarity: AchievementRarity.RARE,
    xpReward: 100,
    criteria: { type: "STREAK_DAYS", target: 7 },
    active: true,
  },
  {
    id: "synergybridge-contributor",
    name: "SynergyBridge Contributor",
    description: "Complete 10 milestones.",
    category: AchievementCategory.PROJECT,
    rarity: AchievementRarity.EPIC,
    xpReward: 250,
    criteria: { type: "MILESTONES_COMPLETED", target: 10 },
    active: true,
  },
];
