export enum ActivityType {
  PROJECT_CREATED = "PROJECT_CREATED",
  MENTOR_ASSIGNED = "MENTOR_ASSIGNED",
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_COMPLETED = "TASK_COMPLETED",
  MILESTONE_CREATED = "MILESTONE_CREATED",
  MILESTONE_COMPLETED = "MILESTONE_COMPLETED",
  FILE_UPLOADED = "FILE_UPLOADED",
  CHAT_MESSAGE = "CHAT_MESSAGE",
  PROJECT_STATUS_CHANGED = "PROJECT_STATUS_CHANGED",
  ORIGINALITY_ASSESSED = "ORIGINALITY_ASSESSED",
  CERTIFICATE_ISSUED = "CERTIFICATE_ISSUED",
  CERTIFICATE_REVOKED = "CERTIFICATE_REVOKED",
  FUNDING_REQUESTED = "FUNDING_REQUESTED",
  FUNDING_APPROVED = "FUNDING_APPROVED",
  FUNDING_REJECTED = "FUNDING_REJECTED",
  FUNDING_DISBURSED = "FUNDING_DISBURSED",
  DIGILOCKER_SYNC_REQUESTED = "DIGILOCKER_SYNC_REQUESTED",
  ABC_SYNC_REQUESTED = "ABC_SYNC_REQUESTED",
  FUNDING_SIGNATURE_ADDED = "FUNDING_SIGNATURE_ADDED",
}

export interface ProjectActivity {
  id: string;
  projectId: string;
  actorId: string;
  actorName: string;
  action: ActivityType;
  entityType: "TASK" | "MILESTONE" | "FILE" | "MESSAGE" | "PROJECT" | "CERTIFICATE" | "FUNDING" | "ORIGINALITY" | "INTEGRATION";
  entityId?: string;
  metadata?: Record<string, unknown> | null;
  createdAt: number;
}
